### ISSUE TITLE
can't install multibeep

### ISSUE THREAD

**Issue by WeiFoo** [automl/multibeep#1]
Hi,

I was trying to run  example_hyperband.py in RoBo, which requires __multibeep__.
However, I encountered the following errors when install it.

```
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from multibeep/util.cpp:485:0:
./include/multibeep/util/posteriors.hpp:5:40: fatal error: boost/math/distributions.hpp: No such file or directory
 #include <boost/math/distributions.hpp>
```

It seems there're no files called distributions.hpp in the folder. Is it missed?

Thanks for help

**Comment by sfalkner** [comment]
The file is part of the Boost library, a very common C++ library. I should add this to the documentation that it is required. You will have to install Boost on your System.On Ubuntu, something like `sudo apt-get install libboost-all-dev` should do the trick. Unfortunately, there is no way to encode C++ dependencies for Python packages, which is why the setup.py doesn't catch that.

**Comment by WeiFoo** [comment]
@sfalkner, sorry to reopen this issue. I still have a couple of questions

> If you want to use the python module without installing it: ''' python setup.py build_ext --inplace '''

I don't understand what does this mean. But I run ```python3 setup.py build_ext --inplace```

When I bring up a interactive python3 session, it seems ```multibeep``` have been installed(?) correctly as I get the fowllowing modules imported

```shell
>>> from robo.solver.hyperband_datasets_size import HyperBand_DataSubsets
>>> from hpolib.benchmarks.ml.svm_benchmark import SvmOnMnist
```


however, when I run ```python3 run_hyperband.py```,  I got the following error message.

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/RoBO-0.2.1-py3.6.egg/robo/solver/hyperband_datasets_size.py", line 10, in <module>
  File "/usr/local/lib/python3.6/site-packages/multibeep/__init__.py", line 3, in <module>
    import multibeep.bandits
ModuleNotFoundError: No module named 'multibeep.bandits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_hyperband.py", line 9, in <module>
    from robo.solver.hyperband_datasets_size import HyperBand_DataSubsets
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/RoBO-0.2.1-py3.6.egg/robo/solver/hyperband_datasets_size.py", line 13, in <module>
ValueError: If you want to use Hyperband you have to install the following dependencies:
multibeep (see https://github.com/automl/multibeep)
```

I can't figure out what's going on here. Thanks for any advice!

**Comment by tinutjoy** [comment]
@WeiFoo , I also faced this issue. After digging a bit into the problem, I have got a small fix. You should make sure you have all cython compiled files in multibeep installation directory. 

Cheers,
